---
all:
  children:
    build_hosts:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

      vars:
        openwrt_version: "v25.12.5"
        openwrt_org: "default"
        openwrt_target: "glinet_gl-mt300n-v2"
        openwrt_captive_portal: false
        openwrt_vpn: "NONE"
        # build/ output/ .ccache/ vengono creati dentro la workdir del repo
        # Jenkins usa la sua workspace, in locale usa la dir del repo
